# Generated by Django 5.1.7 on 2025-04-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='longitude',
        ),
    ]
